#https://github.com/jonathanong/github-actions-workflow-templates/blob/master/node-server/.github/workflows/node.js.yml

name: Node.js CI

on: push

env:
  CODECOV_TOKEN:
  NPM_CONFIG_LOGLEVEL: error
  NPM_CONFIG_JOBS: max
  NPM_CONFIG_PROGRESS: false
  DATABASE_URL: postgres://postgres:postgres@localhost/postgres

jobs:
  test:
    runs-on: self-hosted
    # runs-on: ubuntu-latest


    # services:
    #   https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml
    #   postgres:
    #     image: postgres:latest
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_DB: postgres
    #     ports:
    #       - 5432:5432
    #     # needed because the postgres container does not provide a healthcheck
    #     options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    #   # https://github.com/actions/example-services/blob/master/.github/workflows/redis-service.yml
    #   redis:
    #     image: redis:latest
    #     ports:
    #       - 6379:6379
    #     options: --entrypoint redis-server

    strategy:
      matrix:
        node-version: [18.x]
        # node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
  
    # - run: node -v