name: app-workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Use app-workflow 
      uses: actions/setup-node@v3
    - run:
      npm -v

      